# Header
menu:
  主页: http://takwolf.com
  归档: /archives
  分类: /categories
  标签: /tags
  朋友: /friends
  关于: /about
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/takwolf"
  weibo: "http://weibo.com/takwolf"
  rss: "http://blog.takwolf.com/atom.xml"
  facebook: "https://www.facebook.com/hero.takwolf"
  google: "https://plus.google.com/u/0/101562106204171844130/posts"
  twitter: "https://twitter.com/takgdx"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "http://takwolf.com/img/avatar.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: blog-takwolf
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: Android 和 Web 开发者，痴迷于 Ruby 和 NodeJs，并且像中二病一样写代码！