# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TakWolf 's Blog
subtitle: A 2B Code Monkey
description: Eat Sleep Code Repeat
author: TakWolf
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.takwolf.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gitcafe.com/TakWolfBlog/TakWolfBlog.git
  branch: gitcafe-pages
  message:
  
  
# =============================================================================
# NexT Theme configuration
# =============================================================================

# 多说帐号
duoshuo_shortname: blog-takwolf

# DISQUS 帐号 （如果已经设置 多说 帐号，此选项将被跳过）
disqus_shortname: blog-takwolf

# JiaThis 分享服务
jiathis: false

# 多说 分享服务（必须启用多说）
duoshuo_share: false

# 社交链接，将在侧栏中显示
social:
  GitHub: https://github.com/takwolf
  Facebook: https://facebook.com/hero.takwolf
  Twitter: https://twitter.com/takgdx
  Weibo: http://weibo.com/takwolf
  # 等等


# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa


# Google 站长工具验证，请选择 `HTML Meta` 验证方式
# See: https://www.google.com/webmasters/
google_site_verification: JTaCNLsOuSIYJA_INHvTuTQ3ojx8U_3I4xdqlsMYAeQ


# Google 分析 ID
# See: http://www.google.com/analytics/
google_analytics: UA-65835217-1


# 百度统计 ID，此 ID 是百度统计提供脚本中 hm.js? 后面那串字符，非百度统计帐号
baidu_analytics: 4f6783023cf9e9cfebf54cebb0786835

# 站点起始时间
since: 2014

# =============================================================================
# End NexT Theme configuration
# =============================================================================
